ImageAltOptimizer/ImageAltOptimizer/Controllers/ImageOptimizerController.cs
using ImageAltOptimizer.Data;
using ImageAltOptimizer.Models;
using ImageAltOptimizer.Shopify;
using Newtonsoft.Json;
using ShopifyAPIAdapterLibrary;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImageAltOptimizer.Controllers
{
    public class ImageOptimizerController : Controller
    {
        ShopifyAPIClient shopify;

        [HttpPost]
        public ActionResult UpdateTemplate(string template)
        {
            try
            {
                using (var context = new ImageOptimizerDBEntities())
                {
                    var store = context.Stores.Where(q => q.StoreName == shopify.State.ShopName && q.Active).FirstOrDefault();

                    if (store == null)
                    {
                        return Json(new { success = false, message = "App was install incorrectly. Please reinstall the app." });
                    }
                    else
                    {
                        store.AltTemplate = template;
                        context.SaveChanges();
                        return Json(new { success = true, message = "Template updated" });
                    }
                }
            }
            catch (Exception e)
            {
                return Json(new { success = false, e.Message });
            }
        }

        [HttpPost]
        public ActionResult SyncProductImage()
        {
            try
            {
                var productList = GetAllProducts();

                using (var context = new ImageOptimizerDBEntities())
                {
                    var store = context.Stores.Where(q => q.StoreName == shopify.State.ShopName && q.Active).FirstOrDefault();
                    var template = "";

                    if (store == null)
                    {
                        return Json(new { success = false, message = "App was install incorrectly. Please reinstall the app." });
                    }
                    else
                    {
                        template = store.AltTemplate != null ? store.AltTemplate : ConfigurationManager.AppSettings.Get("DefaultTemplate");
                    }

                    foreach (var product in productList)
                    {
                        var altValue = template
                            .Replace("[product_title]", product.Title)
                            .Replace("[product_type]", product.ProductType)
                            .Replace("[product_vendor]", product.Vendor)
                            .Replace("[shop_name]", shopify.State.ShopName);

                        foreach (var image in product.Images)
                        {

                            var metafieldList = JsonConvert.DeserializeObject<MetafieldListJsonModel>(shopify.Get($"/admin/metafields.json?metafield[owner_id]={image.Id}&metafield[owner_resource]=product_image").ToString());

                            var altMetafield = metafieldList.MetafieldList.Where(q => q.Key == "alt").FirstOrDefault();

                            if (altMetafield == null)
                            {
                                //Create metafield
                                shopify.Post("/admin/metafields.json", new
                                {
                                    metafield = new
                                    {
                                        @namespace = "tags",
                                        key = "alt",
                                        value = altValue,
                                        value_type = "string",
                                        owner_id = image.Id,
                                        owner_resource = "product_image"
                                    }
                                });
                            }
                            else
                            {
                                //Update metafield
                                shopify.Put($"/admin/metafields/{altMetafield.Id}.json", new
                                {
                                    metafield = new
                                    {
                                        id = altMetafield.Id, //metafield id
                                        value = altValue,
                                        value_type = "string"
                                    }
                                });
                            }
                        }
                    }
                }

                return Json(new { success = true, message = "All product images are synced!" });
            }
            catch (Exception e)
            {
                return Json(new { success = false, message = e.Message });
            }
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            ShopifyAuthorizationState authState = ShopifyAuthorize.GetAuthorizationState(this.HttpContext);
            if (authState != null)
            {
                shopify = new ShopifyAPIClient(authState, new JsonDataTranslator());
            }
        }

        private List<ShopifyProductModel> GetAllProducts()
        {
            var productList = JsonConvert.DeserializeObject<ProductListJsonModel>(shopify.Get("/admin/products.json").ToString());

            return productList.ProductList;
        }
    }
}

ImageAltOptimizer/ImageAltOptimizer/Views/App/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<html lang="en">
<head>
    <title>Image Alt Optimizer</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdn.shopify.com/s/assets/external/app.js"></script>
    <script type="text/javascript">
        ShopifyApp.init({
            apiKey: '@ImageAltOptimizer.Models.AppSettings.ApiKey',
            shopOrigin: 'https://baoteststore.myshopify.com',
            debug: true,
            forceRedirect: true
        });
    </script>

    <link rel="stylesheet" media="screen" href="~/Content/app.css">

    @*<script type="text/javascript" async="" src="https://cdn.shopify.com/s/javascripts/tricorder/trekkie.easdk.min.js?v=2017.08.01.1"></script>*@
</head>

<body>
    <div id="wrap">
        <div class="row help-header" style="margin-right:0px;">

            <div class="col-sm-3">
                <div>
                    <img src="/assets/final_bar_logo.png" style="margin-left:26px;margin-top:5px;">
                </div>
            </div>

            <div class="col-sm-9">

                <div style="float: right;margin-right:-15px;">
                    <ul class="help-list">
                        <li><a href="/" class="btn default"><i class="fa fa-dashboard"></i>Dashboard</a></li>
                        <li><a href="/edit" class="btn default"><i class="fa fa-file-code-o"></i>ALT Text</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <form class="edit_shop" id="edit_shop" accept-charset="UTF-8" method="post">
            <div class="section" style="border-bottom: #dee3e8 1px solid;border-bottom:none;">
                <div class="section-summary" style="padding-top:0px;">
                    <h1>Setup Guide</h1>
                    <p>It really is that easy, we'll do the hard work :)</p>
                    <a class="show-shop-faq" target="_blank" href="#"><i class="fa fa-life-ring"></i> FAQ</a>
                </div>
                <div class="section-content">
                    <div class="section-row">
                        <div class="cell-container" style="width:100%;">
                            <div class="cell-column">
                                <div id="section-template" class="flow-section flow-section-quantity success open">
                                    <div class="flow-section-toggle">
                                        <span class="badge-circle">
                                            <span class="step">1</span>
                                        </span>
                                        <span class="title" style="vertical-align: middle;">
                                            Set Template
                                        </span>
                                        <button type="button" class="done-button btn btn-sm btn-primary pull-right" style="vertical-align: middle;background-color: #42ca49;border:none;margin-top:-5px;">
                                            Done
                                        </button>
                                    </div>
                                    <div class="flow-section-content" style="background: #fff;">
                                        <div class="flow-section-content-inner">
                                            <div class="flow-section-white">
                                                <div class="field">
                                                    <input type="text" value="[product_title] - [product_type] - [product_vendor] - [shop_name] - custom text" name="shop[alt_template]" id="shop_alt_template">
                                                    <p style="font-style: italic;font-size: 13px;color: #95a7b7;margin-top: 5px;">
                                                        The following values are available for use. [product_title], [product_type], [product_vendor], [shop_name]
                                                    </p>

                                                    <input type="submit" name="commit" value="Save Template" class="btn btn-primary">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div id="section-sync" class="flow-section flow-section-targeting">
                                    <div class="flow-section-toggle">
                                        <span class="badge-circle">
                                            <span class="step">2</span>
                                        </span>
                                        <span class="title" style="vertical-align: middle;">
                                            Sync Images
                                        </span>
                                        <button type="button" class="btn btn-sm btn-primary pull-right" style="display:none;vertical-align: middle;background-color: #42ca49;border:none;margin-top:-5px;">
                                            Done
                                        </button>
                                    </div>

                                    <div class="flow-section-content" style="background: #fff;">
                                        <div class="flow-section-content-inner">
                                            <div class="flow-section-white">

                                                <div class="field">
                                                    <h3>Status</h3>
                                                    <p>Sync started about 11 hours ago</p>

                                                    <p>Your store is automatically synced every Wednesday at 3am UTC.</p>


                                                    <a class="btn btn-default" id="sync-store" href="#"><i class="fa fa-refresh"></i> Sync Images</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <div id="footer">
        <div class="footer-terms">
            Made with ♥ by Muy Bow. <a style="text-decoration:none;" target="_blank" href="http://boosterapps.net/terms.html">Terms of service</a>
        </div>
    </div>
    <script type="text/javascript">
        $('#edit_shop').on("submit", function (e) {
            e.preventDefault();

            $.ajax({
                method: "POST",
                url: "@Url.Action("UpdateTemplate", "ImageOptimizer")",
                data: {
                    template: $('#shop_alt_template').val()
                },
                success: function (result) {
                    ShopifyApp.Bar.loadingOff();
                    $('#section-template').removeClass('open');
                    $('#section-sync').addClass('open');
                },
                error: function (result) {

                }
            });
        });

        $("#sync-store").click(function () {
            var btn = $(this);
            $.ajax({
                method: "POST",
                url: "@Url.Action("SyncProductImage", "ImageOptimizer")",
                success: function (result) {
                    btn.text("Sync sent to queue");
                    btn.attr("disabled", "disabled");
                    ShopifyApp.Bar.loadingOff();

                    ShopifyApp.Modal.confirm({
                        title: "Sync Started!",
                        message: "Awesome, we've sent your images to be synced! Help keep the app FREE by leaving a quick 10 second review if you like the app, we'd really appreciate it :)",
                        okButton: "Sure!",
                        cancelButton: "No"
                    }, function (result) {
                        if (result == true) {
                            window.parent.location = "https://apps.shopify.com/image-alt-optimizer?reveal_new_review=true"
                        } else {
                            $('#section-sync').removeClass('open');
                            $('#section-compress').addClass('open');
                        }
                    });
                },
                error: function (result) {

                }
            });
        });
    </script>

    @*<script type="text/javascript">
            $(function () {

                var form = $('.edit_shop');
                $(document).on('submit', form, function (e) {
                    var valuesToSubmit = form.serialize();
                    var url = form.attr('action');
                    e.preventDefault();
                    $.ajax({
                        type: "PUT",
                        url: url,
                        data: valuesToSubmit,
                        dataType: "JSON",
                        success: function (data) {
                            ShopifyApp.Bar.loadingOff();
                            $('#section-template').removeClass('open');
                            $('#section-sync').addClass('open');
                        },
                        error: function (data) {
                            ShopifyApp.Bar.loadingOff();
                            ShopifyApp.flashError(data.responseText);
                        }
                    })
                    return false;
                });

                $(document).on('click', '.flow-section-toggle', function () {
                    $('.flow-section').removeClass('open');
                    var section = $(this).parent('.flow-section');
                    section.addClass('open');
                    return false;

                });

                $(document).on('click', '#section-compress .done-button', function () {
                    url = $(this).data('url');
                    window.parent.location = url;
                    return false;
                });


                $(document).on('click', 'a#sync-store', function (e) {
                    var btn = $(this);
                    e.preventDefault();
                    $.ajax({
                        type: "POST",
                        url: "/shops/sync_store",
                        dataType: "JSON",
                        success: function (data) {
                            btn.text("Sync sent to queue");
                            btn.attr("disabled", "disabled");
                            ShopifyApp.Bar.loadingOff();


                            var whShown = getCookie('lionqb-modal-shown');
                            if (whShown == "") {
                                ShopifyApp.Modal.confirm({
                                    title: "Sync Started!",
                                    message: "Awesome, we've sent your images to be synced! Want to try a new FREE Quantity Breaks App?",
                                    okButton: "Sure!",
                                    cancelButton: "No"
                                }, function (result) {
                                    if (result == true) {
                                        window.parent.location = "https://apps.shopify.com/lion-breaks?ref=seo-image-optimizer-sync-modal"
                                    } else {
                                        $('#section-sync').removeClass('open');
                                        $('#section-compress').addClass('open');
                                    }
                                });
                                setCookie('lionqb-modal-shown', 1, 90)
                            } else {
                                ShopifyApp.Modal.confirm({
                                    title: "Sync Started!",
                                    message: "Awesome, we've sent your images to be synced! Help keep the app FREE by leaving a quick 10 second review if you like the app, we'd really appreciate it :)",
                                    okButton: "Sure!",
                                    cancelButton: "No"
                                }, function (result) {
                                    if (result == true) {
                                        window.parent.location = "https://apps.shopify.com/seo-image-optimizer?reveal_new_review=true"
                                    } else {
                                        $('#section-sync').removeClass('open');
                                        $('#section-compress').addClass('open');
                                    }
                                });
                            }





                        },
                        error: function (data) {
                            ShopifyApp.Bar.loadingOff();
                            ShopifyApp.flashError(data.responseText);
                        }
                    });
                    return false;
                });
            });
        </script>*@
</body>
</html>